[pytest]
testpaths = tests_TC
python_files = test_*.py *_test.py *.py
markers =
#Demo
    ; tc01: Đăng nhập
    ; tc02: Đăng ký gói D5 màn trang chủ
    ; tc03: Đăng ký gói D5 màn tìm kiếm
    ; tc04: Đăng ký gói D5 màn tất cả gói cước
    ; tc05: Đăng ký gói D5 màn mua gói - gói thường
    ; tc06: Đăng ký gói D5 màn mua gói - Tạo gói cước linh hoạt
    ; tc07: Huỷ gói mà trang chủ
    ; tc08: Huỷ gói màn tìm kiếm
    ; tc09: Huỷ gói màn tất cả gói cước
    ; tc10: Huỷ gói mua gói - gói thường
    ; tc11: Huỷ gói D5 màn mua gói - Tạo gói cước linh hoạt
#=============HOMEPAGE=================
    tc01: Search gói cước có trong DB
    tc02: Search gói cước không có trong DB
    tc03: Search gói dịch vụ có trong DB
    tc04: Click avata
    tc05: 
    tc06:
    tc07:
    tc08:
    tc09:
    tc10:
    tc11:
    tc12:
    tc13: 
    tc13_1:
    tc13_2:
    tc14:
    tc15:
    tc16:
    tc17:
    tc18:
    tc19:
    tc20:
    tc21:
    tc22:
    tc23:
    tc24:
    tc25:
    tc26:
    tc27:
    tc28:
    tc29:
    tc30:
