[pytest]
testpaths = tests_TC
python_files = test_*.py *_test.py *.py
markers =
#=============HOMEPAGE=================
    tc01: Search gói cước có trong DB
    tc02: Search gói cước không có trong DB
    tc03: Search gói dịch vụ có trong DB
    tc04: Click avata
    tc05: 
    tc06:
    tc07:
    tc08:
    tc09:
    tc10:
    tc11:
    tc12:
    tc13: 
    tc13_1:
    tc13_2:
    tc14:
    tc15:
    tc16:
    tc17:
    tc18:
    tc19:
    tc20:
    tc21:
    tc22:
    tc23:
    tc24:
    tc25:
    tc26:
    tc27:
    tc28:
    tc29:
    tc30:
    tc30_1:
    tc30_2:
    tc30_3:
    tc31:
    tc31_2:
    tc31_3:
    tc31_4:
    tc32:
    tc32_1:
    tc32_2:
    tc32_3:
    tc32_4:
    tc33:
    tc34:
    tc35:
    tc36:
    tc37:
    tc38:
    tc39:
    tc40:

#=============BUY PAKAGE===============
    tc41:
    tc42:
    tc43:
    tc44:
    tc45:
    tc46:
    tc47:
    tc47_1:
    tc47_2:
    tc48:
    tc48_1:
    tc48_2:
    tc49:
    tc50:
    tc51:
    tc52:
    tc52_1:
    tc53:
    tc54:
    tc55:
    tc56:
    tc56_1:
    tc57:
    tc57_1:
    tc58:
    tc59:
    tc60:
    tc61:
    tc62:
    tc63:
    tc64:
    tc65:
    tc66:
    tc67:
    tc68:
    tc69:
    tc70:


